version: "3.9"
services:
  control-node:
    depends_on:
      - worker
    image: saturation-control-node:latest
    networks:
      - saturation-network
    volumes:
      #- ~/:/saturation/ # read/write access to home directory
      - ./:/saturation/ # directory of docker compose file
      # parameter volume
    command: ${APPROACH} ${NUM_WORKERS} ${BENCHMARK}
    ports:
      - "30000"
  worker:
    image: saturation-worker:latest
    networks:
      - saturation-network
    ports:
      - "30000"
    command: 0.0.0.0 30000 1
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS}

networks:
  saturation-network: { }
