version: "3.9"
services:
  control-node:
    image: saturation-control-node:latest
    networks:
      - saturation-network
    volumes:
      - ~/:/saturation # read/write access to home directory
    environment:
      - NUM_WORKERS=${NUM_WORKERS}
      - PORT=${CONTROL_NODE_PORT}
      - BENCHMARK=${BENCHMARK}
    command: ${NUM_WORKERS} ${PORT} ${BENCHMARK}
#  workers:
#    image: saturation-worker-node:latest
#    depends_on:
#      - control-node
#    networks:
#      - saturation-network
#    environment:
#      - PORT = ${CONTROL_NODE_PORT}

networks:
  saturation-network: { }
