package enums;

public enum SaturationStatusMessage {
    CONTROL_NODE_REQUESTS_SATURATION_INTERRUPT,
    CONTROL_NODE_REQUESTS_START_SATURATION,
    CONTROL_NODE_REQUESTS_SATURATION_CONTINUATION,
    CONTROL_NODE_REQUESTS_SATURATION_STATUS,
    CONTROL_NODE_INFO_ALL_PARTITIONS_CONVERGED,
    PARTITION_INFO_TODO_IS_EMPTY,
    PARTITION_INFO_INITIALIZED,
    PARTITION_INFO_SATURATION_INTERRUPTED,
    PARTITION_INFO_SATURATION_RUNNING,
    PARTITION_INFO_SATURATION_CONVERGED,
    PARTITION_SERVER_HELLO,
    PARTITION_CLIENT_HELLO
}
