package enums;

public enum SaturationStatusMessage {
    //CONTROL_NODE_REQUESTS_SATURATION_CONTINUATION,
    //CONTROL_NODE_REQUESTS_SATURATION_STATUS,
    //CONTROL_NODE_REQUESTS_SATURATION_INTERRUPT,
    //WORKER_INFO_TODO_IS_EMPTY,
    //WORKER_INFO_SATURATION_INTERRUPTED,
    //WORKER_INFO_INITIALIZED,
    //CONTROL_NODE_REQUESTS_START_SATURATION,
    //WORKER_INFO_SATURATION_RUNNING,
    //WORKER_INFO_SATURATION_CONVERGED,
    CONTROL_NODE_INFO_ALL_WORKERS_INITIALIZED,
    CONTROL_NODE_REQUEST_SEND_CLOSURE_RESULT,
    WORKER_SERVER_HELLO,
    WORKER_CLIENT_HELLO
}
