package enums;

public enum SaturationApproach {
    SINGLE_THREADED,
    PARALLEL,
    DISTRIBUTED_SEPARATE_JVM,
    DISTRIBUTED_MULTITHREADED,
    DISTRIBUTED_SEPARATE_DOCKER_CONTAINER,
    DISTRIBUTED_DOCKER_BENCHMARK
}
