package enums;

public enum StatisticsComponent {
    CONTROL_NODE_INITIALIZING_ALL_WORKERS,
    CONTROL_NODE_SATURATION_TIME,
    CONTROL_NODE_WAITING_FOR_CLOSURE_RESULTS,
    WORKER_INITIALIZING_OTHER_WORKER_CONNECTIONS,
    WORKER_WAITING_TIME_SATURATION,
    WORKER_APPLYING_RULES_TIME_SATURATION,
}
